#============================================================================================================================|
#   _________.__                    ___ ___ .__          __
# /   _____/|  |__   ____ ______  /   |   \|__| _______/  |_  ___________ ___.__.
# \_____  \ |  |  \ /  _ \\____ \/    ~    \  |/  ___/\   __\/  _ \_  __ <   |  |
# /        \|   Y  (  <_> )  |_> >    Y    /  |\___ \  |  | (  <_> )  | \/\___  |
#/_______  /|___|  /\____/|   __/ \___|_  /|__/____  > |__|  \____/|__|   / ____|
#        \/      \/       |__|          \/         \/                     \/
#============================================================================================================================|
#
# Author's Discord: Morphie#1738
# This plugin is dependent on Quickshop (Remake)
# https://www.spigotmc.org/resources/quickshop-reremake-1-19-ready-multi-currency.62575/
#
#============================================================================================================================|

Settings:
  # If set to true the plugin will use the item the player is buying/selling as the shop icon in the menu
  UseShopItem: true
  # Should the plugin automatically delete player data files within the ShopHistory/PlayerData files folder? (This system is in
  # place to help trim files of players who may never rejoin the server.)
  AutoDeletePlayerFiles:
    Enabled: false
    # Number of days a player has to be offline before attempting to remove their player file.
    DaysTillDeletion: 30

#============================================================================================================================|

Menu:
# ShopItem: This will only work if the "UseShopItem" setting above us set to 'true'
  ShopItem:
    Material: "CHEST"
    CustomModelID: 1
  EmptyStockItem:
    Material: "BARRIER"
    CustomModelID: 1
  FillerItem:
    Material: "GRAY_STAINED_GLASS_PANE"
    CustomModelID: 1
  NextPage:
    Material: "ARROW"
    CustomModelID: 1
  PrevPage:
    Material: "ARROW"
    CustomModelID: 1

#============================================================================================================================|