#============================================================================================================================|
#   _________.__                    ___ ___ .__          __
# /   _____/|  |__   ____ ______  /   |   \|__| _______/  |_  ___________ ___.__.
# \_____  \ |  |  \ /  _ \\____ \/    ~    \  |/  ___/\   __\/  _ \_  __ <   |  |
# /        \|   Y  (  <_> )  |_> >    Y    /  |\___ \  |  | (  <_> )  | \/\___  |
#/_______  /|___|  /\____/|   __/ \___|_  /|__/____  > |__|  \____/|__|   / ____|
#        \/      \/       |__|          \/         \/                     \/
#============================================================================================================================|
#
# Author's Discord: Morphie#1738
# This plugin is dependent on Quickshop (Remake)
# https://www.spigotmc.org/resources/quickshop-reremake-1-19-ready-multi-currency.62575/
#
#============================================================================================================================|

Settings:
  # If set to true the plugin will use the item the player is selling as the shop icon in the menu
  UseShopItem: true

#============================================================================================================================|

Menu:
  FillerItem:
    Material: "PAPER"
    CustomModelID: 10040
# ShopItem: This will only work if the "UseShopItem" setting above us set to 'true'
  ShopItem:
    Material: "PAPER"
    CustomModelID: 1
  EmptyStockItem:
    Material: "BARRIER"
    CustomModelID: 1
  FilterItem:
    Material: "PAPER"
    CustomModelID: 1
  NextPage:
    Material: "ARROW"
    CustomModelID: 1
  PrevPage:
    Material: "ARROW"
    CustomModelID: 1

#============================================================================================================================|