#============================================================================================================================|
#   _________.__                    ___ ___ .__          __
# /   _____/|  |__   ____ ______  /   |   \|__| _______/  |_  ___________ ___.__.
# \_____  \ |  |  \ /  _ \\____ \/    ~    \  |/  ___/\   __\/  _ \_  __ <   |  |
# /        \|   Y  (  <_> )  |_> >    Y    /  |\___ \  |  | (  <_> )  | \/\___  |
#/_______  /|___|  /\____/|   __/ \___|_  /|__/____  > |__|  \____/|__|   / ____|
#        \/      \/       |__|          \/         \/                     \/
#============================================================================================================================|
#
# Author's Discord: Morphie#1738
# This plugin is dependent on
#
#============================================================================================================================|
